# Generated by Django 4.1.5 on 2023-04-06 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitems',
            old_name='thecart',
            new_name='cart',
        ),
        migrations.RenameField(
            model_name='cartitems',
            old_name='themedicine',
            new_name='medicine',
        ),
    ]
