# Generated by Django 4.1.5 on 2023-04-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_thecart_cartitems_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carts',
            name='instamojo_id',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
